### ISSUE TITLE
No data for some countries

### ISSUE THREAD

**Issue by vovodroid** [dkobak/excess-mortality#4]
There is no Excess per 100k  and  Excess as % of annual baseline columns for some countries, for instance Finland, Norway and more.

**Comment by dkobak** [comment]
For these countries the excess mortality is not significantly different from zero. We decided not to provide these normalized measures in this case, as they can be misleading (e.g. look misleadingly large even though in fact not significantly different from zero.)

**Comment by vovodroid** [comment]
>look misleadingly large even though in fact not significantly different from zero
Why? How 0.5% would be misleading?

**Comment by dkobak** [comment]
You are probably right that these two columns (per 100k and as %) won't be misleading. What can be misleading is the "undercount ratio". For example, in Hong Kong it comes around 20, because the excess mortality is ~2000 (not significantly different from 0 though) but the official number of covid deaths is ~100.

I could fill it in the per100k and the % columns and only leave nans in the undercount column. Or fill everything in and hope nobody will be misled.

What do you think? CC @akarlinsky.

**Comment by vovodroid** [comment]
So what is decision?

**Comment by dkobak** [comment]
Thanks for the reminder. I have added to the CSV file the excess per 100k and the excess as a % of annual for countries where excess is not significantly different from zero.

**Comment by vovodroid** [comment]
Great, much better know!

By a way, are you preparing for second year circle? It's soon will be here.
